### ISSUE TITLE
Automate this publication

### ISSUE THREAD

**Issue by engelgabriel** [flathub/chat.rocket.RocketChat#1]
Hi, thank you so much for this! 

Is there anything we can do to automate this publishing? Could we add this to our repository and have an official release?

REFS: https://github.com/RocketChat/Rocket.Chat.Electron/issues/770

**Comment by TingPing** [comment]
We can give you commit access here and you can have whatever automation push changes here.

**Comment by engelgabriel** [comment]
Thanks!

**Comment by TingPing** [comment]
Let me know if you want me to add anybody else.
