### ISSUE TITLE
Missing icons after username change

### ISSUE THREAD

**Issue by ondrejkolin** [flathub/chat.rocket.RocketChat#14]
We are migrating users to LDAP, which involves changing usernames. After this done, user have missing profile pictures. They can reupload it, but it is ignored by flatpaked Rocket.chat either web version and mobile app are fine. Reloading with ignoring the cache is not helping:

How to test the issue:
- Create user with a profile pic
- Change his username
- Upload new profile picture
- This new picture after reloading the flatpak version will be missing.

**Comment by andrevmatos** [comment]
Looks like an upstream issue; if it persists on latest build, please, try resetting the application data, `rm -rv ~/.var/app/chat.rocket.RocketChat/`.
