### ISSUE TITLE
Certificates are not trusted by default

### ISSUE THREAD

**Issue by tobiasbaehr** [flathub/chat.rocket.RocketChat#35]
I do not know If I am just to stupid to understand flatpak or this is a bug.

Since a few days I need to manually confirm new certificates which are then stored under:

`~/.var/app/chat.rocket.RocketChat/config/Rocket.Chat/certificates.json`

(I reinstalled rocketchat already + cleaned data)

Has it something todo with https://formulae.brew.sh/formula/p11-kit ? Which is required by some other homebrew packages.

**Comment by andrevmatos** [comment]
This is a server/upstream issue, I can't reproduce it locally with latest build. Please, let me know if the problem persists.
