### ISSUE TITLE
Missing spell correction

### ISSUE THREAD

**Issue by bellegarde-c** [flathub/chat.rocket.RocketChat#36]
Looks like ArchLinux is using a patch for this:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=rocketchat-desktop

**Comment by andrevmatos** [comment]
This is not about a patch. Flatpak apps usually don't have access to system's folders or resources, and need to bundle its own files and libraries. RocketChat includes a collection of dictionaries, which should be available, but giving it access to system's may not be feasible, but I'll check.

**Comment by bellegarde-c** [comment]
You need to copy LibreOffice dictionnaries:

```
cd /srv/opt/Rocket.Chat/resources/dictionaries/
[gnumdk@arch dictionaries]$ l
de_DE.aff  en_GB.aff  en_US.aff  es_ES.aff  fr_FR.aff  pt_BR.aff
de_DE.dic  en_GB.dic  en_US.dic  es_ES.dic  fr_FR.dic  pt_BR.dic

```

FR added on a Fedora 32 with official rocket chat package.

**Comment by andrevmatos** [comment]
I can see a few tens of languages on current build, all distributed by the upstream package, and should be enough for anyone running this.
