### ISSUE TITLE
3.0.0 bug won't allow connect to self-hosted servers

### ISSUE THREAD

**Issue by lasombra** [flathub/chat.rocket.RocketChat#41]
https://github.com/RocketChat/Rocket.Chat.Electron/issues/1743

Fixed on 3.0.1

**Comment by lasombra** [comment]
Should be fixed by https://github.com/flathub/chat.rocket.RocketChat/pull/42

**Comment by cho2** [comment]
```
flatpak run chat.rocket.RocketChat
[bugsnag] Loaded!
Gtk-Message: 15:05:59.211: Failed to load module "canberra-gtk-module"
Gtk-Message: 15:05:59.297: Failed to load module "canberra-gtk-module"
Gtk-Message: 15:05:59.297: Failed to load module "canberra-gtk-module"
SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at /app/Rocket.Chat/resources/app.asar/app/main.js:1344:42
    at Generator.next (<anonymous>)
    at /app/Rocket.Chat/resources/app.asar/node_modules/tslib/tslib.js:114:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/app/Rocket.Chat/resources/app.asar/node_modules/tslib/tslib.js:110:16)
    at setupServers (/app/Rocket.Chat/resources/app.asar/app/main.js:1280:46)
    at /app/Rocket.Chat/resources/app.asar/app/main.js:3225:11
    at Generator.next (<anonymous>)
    at fulfilled (/app/Rocket.Chat/resources/app.asar/node_modules/tslib/tslib.js:111:62)
[bugsnag] Unhandled rejection…
TypeError: Error processing argument at index 0, conversion failure from 
    at BrowserWindow.setBounds (electron/js2c/browser_init.js:29:405)
    at applyRootWindowState (/app/Rocket.Chat/resources/app.asar/app/main.js:760:20)
    at /app/Rocket.Chat/resources/app.asar/app/main.js:3241:5
    at Generator.next (<anonymous>)
    at fulfilled (/app/Rocket.Chat/resources/app.asar/node_modules/tslib/tslib.js:111:62)
```

**Comment by lasombra** [comment]
Weird, it's running here, but seems related to this: https://github.com/RocketChat/Rocket.Chat.Electron/issues/1753

**Comment by TaLoN1x** [comment]
still doesnt work on 3.0.1

**Comment by jamellyf** [comment]
Same problem for me, not working on 3.0.1

**Comment by aklink** [comment]
Same problem. Does not work with 3.0.1 on Ubuntu 18.04

**Comment by andrevmatos** [comment]
This is an upstream issue. Please, refer to https://github.com/RocketChat/Rocket.Chat.Electron/issues/1764 or any of the several other issues recently opened on their repo. Can't do anything on our side, just wait for a new hotfix version.

**Comment by andrevmatos** [comment]
3.0.2 also didn't make it work for me. Workaround is to input `https://open.rocket.chat` on the server screen, quitting before logging in, then editing `.var/app/chat.rocket.RocketChat/config/Rocket.Chat/config.json` and replacing a couple of `https://open.rocket.chat` entries present on this JSON (and possibly also replacing the `favicon`, if desired). Then, launching the app again will take you straight to the login of your custom server.

**Comment by jamellyf** [comment]
The upstream issue is already solved, maybe someone could close this issue.

**Comment by andrevmatos** [comment]
Yes, it works for me. Reopen if needed. Thanks
