### ISSUE TITLE
Notifications not working (KDE, Fedora 34)

### ISSUE THREAD

**Issue by markusdd** [flathub/chat.rocket.RocketChat#56]
Hi,

I am using rocketchat installed by flatpak on a Fedora 34 system with Plasma desktop.

I have noticed notifications are not working anymore.

I get the 'bing' sound and in the taskbar the application Icon flashes ornage, but the message notifications are not popping up
anymore.

Also, rocketchat does not appear in the notification setup in the KDE system settings, other flatpak apps like Spotify do.

Is this a known issue? Any idea on this? Is maybe a packaging option like `--talk-name=org.kde.StatusNotifierWatcher` missing?

**Comment by andrevmatos** [comment]
Upstream issue: https://github.com/RocketChat/Rocket.Chat.Electron/issues/2007

**Comment by andrevmatos** [comment]
Fixed in #59
