### ISSUE TITLE
High CPU usage since 3.3.0

### ISSUE THREAD

**Issue by bellegarde-c** [flathub/chat.rocket.RocketChat#58]
Since 3.3.0, my CPU usage is around 70% making my laptop fans crazy.

This fix the issue:
` flatpak update --commit=5e459ed5727bf41145ac9a54e852fed70b9583548dcd2fdd0ef6b8263dff79ae chat.rocket.RocketChat`

**Comment by andrevmatos** [comment]
Upstream issue: https://github.com/RocketChat/Rocket.Chat.Electron/issues/2068
3.3.0 was revoked from release, I'm not sure how to downgrade on Flathub, but I'll check.

**Comment by andrevmatos** [comment]
Closed by bb806f79596016e75da172d5c6052788e8f239fd
