### ISSUE TITLE
Can't click on hyperlinks

### ISSUE THREAD

**Issue by megamaced** [flathub/chat.rocket.RocketChat#7]
If a message is posted containing a url, the url cannot be clicked to open in an external web browser

**Comment by megamaced** [comment]
This works in the rpm, but not the flatpak version

**Comment by andrevmatos** [comment]
Hi, @megamaced . Thank you for your bug report. I saw this bug while migrating from the pre-compiled base to the self-compiling flatpak version (last commits in this repo), but `flathub` is going over some maintenance, so it still didn't build/updated this version nor the update to v2.14.0 which I just merged. You can wait a little to get the update, or build it yourself from the files here, which is pretty straightforward too, as simple as `flatpak-builder --repo=../repo --force-clean build-dir chat.rocket.RocketChat.json` inside this repository folder, and setting `../repo` as a local user repository (see [flatpak-builder tutorial](http://docs.flatpak.org/en/latest/first-build.html#put-the-app-in-a-repository) for details).
I'll close this issue once the flathub package gets updated, and you can re-open if the issue persists. Thank you

**Comment by andrevmatos** [comment]
Flathub's package is updated to 2.14.0, just tested here and it's working. Please, reopen if the issue persists for you

**Comment by lasombra** [comment]
I'm seeing this issue on 2.15.0. Funny thing is that not even right-click works.
