### ISSUE TITLE
3.5.7 vs 3.5.6

### ISSUE THREAD

**Issue by mokilcde** [flathub/chat.rocket.RocketChat#70]
Hi!

In the git repo you have version 3.5.7 but on your flathub page it is 3.5.6 and also on my system (Debian Sid)

Why that

**Comment by TimmiORG** [comment]
Hm, flathub is still not providing the latest version:
https://flathub.org/apps/details/chat.rocket.RocketChat

**Comment by andrevmatos** [comment]
@TingPing do you know what's happening here? Today I merged #72 , which was supposed to already go to flathub's repo, but [the webUI](https://flathub.org/apps/details/chat.rocket.RocketChat) still shows `3.5.6`, from September. Did any other action became a requirement for updates besides merging the update PR?

**Comment by TingPing** [comment]
No, it looks fine: https://flathub.org/builds/#/builders/32/builds/67662

Maybe an appdata problem but it also looked fine.

**Comment by andrevmatos** [comment]
It's up-to-date now. Thanks.
